# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Manu S.K
email: "kashika24@gmail.com"
description: >
  Ambitious Machine Learning enthusiast and eager person to learn new technology. I am passionate about programming. Interested in ML,AI and Cloud Computing.
about_me: >
  I am a results-driven software engineer with over 4 years of experience and a strong foundation in computer
science principles and research. Skilled in developing and implementing machine learning frameworks and
libraries. I have a proven track record of delivering successful projects for clients in the automobile and
banking industries. My passion lies in artificial intelligence and deep learning, where I continuously seek to
expand my knowledge and skills. I thrive in problem-solving and effectively collaborate with cross-functional
teams to drive project success
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manu-sk.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
linked_in_link: "https://www.linkedin.com/in/manu-s-k-1b373ba2/"
github_link: "https://www.github.com/manu-sk"
twitter_username: "@_SK_Manu"
google_analytics_id: 'UA-117297510-1'
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
